marker_sets:
  RD2-Liver-All:
    zonation: Glul, Oat, Cyp2a5, Mup9, Mup17, Cyp2c29, Cyp2e1, Mup11, Hamp, Ass1, Serpina1e, Cyp2f2, Alb, Mup20
    Macro: Cd5l, Cd74, Clec4f, H2-Ab1, C1qb, H2-Aa, C1qc, Csf1r, Ctss, Lyz2,
    ENDO: Aqp1, Dnase1l3, Gpr182, Gpihbp1, Kdr,
    Hep_Injured: Saa1, Saa2, Saa3
    HPC: Spp1, Mmp7, Clu
    Mf-Inflamed: Cd74, H2-Ab1, H2-Aa, H2-Eb1
    Mf_Kupffer: Cbgl, Marco, Clec4f, C1qc, C1qb, Cfp, Fcna, Csf1r, C1qa
    HSC-A: Col3a1, Col1a1, Col1a2, Mgp, Vwf, Col6a1, Adamtsl2, Gsn, Tagln, Acta2, Serpinh1, Timp1, Gja5, Bgn, Myl9, Fstl1, Tpm2, Col6a2, Flna, Col4a1, Sparc, Vim
  HD7-HLJLG-UCSD-Liver:
    Hep_Lipo1: Mup3, Apoa2, Apoc3
    Hep_Hamp: Hamp, Ahsg, Igfbp1, Fgb
    Hep_PP1: Mup20
    HPC: Spp1, Clu
    Hep_Lipo2: Apoa4, Apoa2, Scd1, Apoc3
    Macro: Cd74, H2-Aa, H2-Ab1, Lyz2, H2-Eb1, Ctsb, Lyz2
    Hep_PP2: Gstm1, Alb, Gsta1, Gc
    HSC-A: Col3a1, Col1a1, Col1a2, Igfbp7
    Hep_inj: Saa1, Saa2
    RBC: Hbb-bs, Hba-a1, Hba-a2
    B_cell: Igha, Igj, Igkc
    SM: Tagln, Actg2, Myl9, Tpm2, Cnn1, Acta2
  HD30-inj-colon-comb:
    Fibro: Col3a1
    Goblet: Zg16, Tff3,Clca3,Spink3
    EEC: Pyy,Insl5,ppy
    SM: Tagln,Acta2,Cnn1,Tpm2,Myl9
    Colonocyte: Saa1,Lypd8,Sepp1,Prdx6,Car4
    B_cell: Igha,Igj
    Macro: Ctsb
    Injury: Sprr2a3,Lamc2,2010109I03Rik,Clu,F3,Anxa2,Anxa1
    Neuronal: Vip,Gal,Uchl1
  HD13-HLJNG-L1:
    TypeI: Tnnt1, Tnnc1, Tpm3, Atp2a2, Myh7, Myl2, Tnni1, Myl3
    TypeIIa: Myh1
    TypeIIx: Myh2
    NMJ: Prkar1a, Cd24a
    Fibroblasts: Gsn, Dcn, Fbn1
    Macrophages: Cd74, H2-Ab1, H2-Aa, Retnla, Lyz2
    Endothelial: Aqp1, Ptrf
    Nuclear: Malat1, Neat1
